// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AImage: typeof import('ant-design-vue/es')['Image']
    ImageBox: typeof import('./.vitepress/components/image-box/index.vue')['default']
    NavUl: typeof import('./.vitepress/components/nav-ul/index.vue')['default']
  }
}
